package openai

import (
	"context"
	"fmt"
	"strings"
	"time"
	"encoding/json"

	"aiops-gateway/internal/config"
	"aiops-gateway/internal/llm"

	"github.com/openai/openai-go/v3"
	"github.com/openai/openai-go/v3/option"
)

type Client struct {
	client      openai.Client
	model       string
	temperature float64
}

func NewClient(cfg config.AIConfig) *Client {
	timeout := cfg.Timeout
	if timeout <= 0 {
		timeout = 60 * time.Second
	}

	opts := []option.RequestOption{
		option.WithAPIKey(cfg.APIKey),
		option.WithRequestTimeout(timeout),
	}

	if cfg.BaseURL != "" {
		opts = append(opts, option.WithBaseURL(strings.TrimRight(cfg.BaseURL, "/")))
	}

	return &Client{
		client:      openai.NewClient(opts...),
		model:       cfg.Model,
		temperature: cfg.Temperature,
	}
}

func (c *Client) RawChatJSON(ctx context.Context, msg []llm.Message, schema any) (content string, raw string, err error) {
	if len(msg) == 0 {
		return "", "", fmt.Errorf("消息列表为空")
	}

	messages := make([]openai.ChatCompletionMessageParamUnion, 0, len(msg))
	for _, m := range msg {
		switch m.Role {
		case llm.RoleSystem:
			messages = append(messages, openai.SystemMessage(m.Content))
		case llm.RoleUser:
			messages = append(messages, openai.UserMessage(m.Content))
		case llm.RoleAssistant:
			messages = append(messages, openai.AssistantMessage(m.Content))
		default:
			return "", "", fmt.Errorf("不支持的消息角色: %s", m.Role)
		}
	}

	schemaParam := openai.ResponseFormatJSONSchemaJSONSchemaParam{
		Name:        "structured_response",
		Description: openai.String("Structured response generated by the model"),
		Schema:      schema,
		Strict:      openai.Bool(true),
	}

	params := openai.ChatCompletionNewParams{
		Model:    openai.ChatModel(c.model),
		Messages: messages,
		ResponseFormat: openai.ChatCompletionNewParamsResponseFormatUnion{
			OfJSONSchema: &openai.ResponseFormatJSONSchemaParam{
				JSONSchema: schemaParam,
			},
		},
	}

	if c.temperature > 0 {
		params.Temperature = openai.Float(c.temperature)
	}

	resp, err := c.client.Chat.Completions.New(ctx, params)
	if err != nil {
		return "", "", fmt.Errorf("调用 OpenAI-compatible LLM 失败: %w", err)
	}

	if len(resp.Choices) == 0 {
		return "", "", fmt.Errorf("LLM 响应 choices 为空")
	}

	content = resp.Choices[0].Message.Content
	if content == "" {
		return "", "", fmt.Errorf("LLM 响应 content 为空")
	}

	rawBytes, _ := json.Marshal(resp)
	return content, string(rawBytes), nil
}
